### ISSUE TITLE
compile error in PPA

### ISSUE THREAD

**Issue by mango-vdr** [notspiff/visualization.waveform#11]
`CMakeFiles/visualization.waveform.dir/src/Main.cpp.o -c /<<PKGBUILDDIR>>/src/Main.cpp
/<<PKGBUILDDIR>>/src/Main.cpp:32:20: fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>`
please add build-depends "libglu1-mesa-dev" in debian/control

lg
mango

**Comment by notspiff** [comment]
now fixed, sorry for delay and thanks for report.
