### ISSUE TITLE
Kodi locks up when playing back 96khz 5.1 tracks

### ISSUE THREAD

**Issue by snake3ca** [notspiff/visualization.waveform#17]
When using the waveform visualization on Kodi 18 on Ubuntu it locks Kodi up when playing back 96khz or higher 5.1 tracks.

96khz and higher 2.0 tracks work fine. 

44.1 & 48 khz 5.1 tracks also work fine.

**Comment by AlwinEsch** [comment]
Have looked it seems to be a problem on Kodi itself, only on this addon more visible. 

On my system it has worked with 96khz 5.1 (but is a bit more heavy system), to become your Problem I must taken from http://www.2l.no/hires/ the 5.1 Surround DSD 64 2.8224Mbit/s examples (control and normal GUI was still OK).

Was by you only locked on visualization view or complete control to Kodi not possible?

**Comment by snake3ca** [comment]
Hi DSD likely converts to 88.2khz pcm. Might be working fine at that rate. Also I have found it only crashes using nvidia gpu, on a intel gpu it just doesnt render any waveform.

Try with this 5.1 demo file

http://www.lindberg.no/hires/test/2L-145/2L-145_mch_FLAC_96k_24b_01.flac

Thanks for looking into the issue.

**Comment by AlwinEsch** [comment]
Maybe it works after this change here better: https://github.com/xbmc/visualization.waveform/pull/26

**Comment by snake3ca** [comment]
Hi i tried the latest build pushed to the ubuntu ppa and it still crashes with 96khz 5.1 tracks.

**Comment by AlwinEsch** [comment]
Can you also install `kodi-visualization-waveform-dbg` and make a backtrace.
And which CPU/GPU system you use?

e.g.
```bash
kodi # Start Kodi
sudo gdb --pid=`pidof kodi-x11` # Link debug to Kodi
# WAIT FOR CRASH, Following commands inside gdb
bt # Get the thread back trace where produced crash
thread apply all bt # Get the thread back trace of all on Kodi
q # Exit gdb
```

**Comment by snake3ca** [comment]
CPU: Intel(R) Core(TM) i3-3220T
GPU: GeForce GT 1030  (On a intel GPU it doesnt lockup Kodi but simply doesnt display the waveform at all)

I Attached the back trace log with the Nvidia GPU.
[backrace.log](https://github.com/xbmc/visualization.waveform/files/3800615/backrace.log)

**Comment by AlwinEsch** [comment]
After a long time I was come to fix this part where I becomed files where produce it at home, see fix request here https://github.com/xbmc/xbmc/pull/18294

Fault not relate to addon, is coming from Kodi itself.

**Comment by AlwinEsch** [comment]
With Kodi Matrix, can this error be seen as fixed?

**Comment by snake3ca** [comment]
On the Kodi Matrix nightly this bug does not appear to be present. Looks like its fixed.
