### ISSUE TITLE
Line strenght

### ISSUE THREAD

**Issue by peat80** [notspiff/visualization.waveform#29]
Not an issue but a feature request:

Would it be possible to add a line strenght setting so that one can configure thicker lines for the visualization?

**Comment by AlwinEsch** [comment]
Why not :smile:, sound good and I look to bring it

**Comment by peat80** [comment]
Awesome. That would be really cool. I like the waveform viz, but its hard to see that thin lines, especially with coloured background. 😃👌

**Comment by AlwinEsch** [comment]
Change is in it. In order to change the line thickness at Kodi Leia, its version 18.5 is needed.

https://github.com/xbmc/xbmc/pull/16856

**Comment by peat80** [comment]
Wow, that was fast. 😎👌
Only Kodi 18.4 here on latest LibreElec so testing this will have to wait a little. 
Anyways thanks for the effort. 👍
